#!/usr/bin/env Rscript
# Make finshbone plots from a csv file generated by fitting hmm model

library(reshape2)
library(ggplot2)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(gridExtra)
library(logging)

# Test data set
# alnData = "/pbi/dept/secondary/siv/smrtlink/smrtlink-internal/userdata/jobs-root/005/005440/tasks/pbalign.tasks.consolidate_alignments-0/combined.alignmentset.xml"
# tmp = loadPBI(alnData)
# bam = tmp$file[1]
# fasta = "/pbi/dept/secondary/siv/smrtlink/smrtlink-internal/userdata/jobs-root/005/005437/pacbio-reference/HLA_A_NA12878_8x_unrolled/sequence/HLA_A_NA12878_8x_unrolled.fasta"
#
# input_csv = "/home/ytian/Project/ITG-5/errormode-3.csv"
# img_path = "/home/ytian/Project/ITG-5/"

# Define a basic addition to all plots
plTheme <- theme_bw(base_size = 18)
clScale <- scale_colour_brewer(palette = "Set1")
clFillScale <- scale_fill_brewer(palette = "Set1")
themeTilt = theme(axis.text.x = element_text(size = 11, angle = 45, hjust = 1))
pd <- position_dodge(0.2)

makeFishbonePlots <- function(input_csv, img_path) {
  loginfo("Making FishbonePlots plots")
  
  # Read HMM error from the csv file
  errormode <- read.csv(input_csv)
  
  # Filter the ZMWs with SNR = 0
  errormode = errormode[!errormode$SNR_A == 0,]
  breaks = c(0, 1:40)/2
  
  # Subset by context and set breaks for SNR values
  errormodeA <- errormode[,c(1,4*c(1:11) - 2)]
  errormodeC <- errormode[,c(1,4*c(1:11) - 1)]
  errormodeG <- errormode[,c(1,4*c(1:11))]
  errormodeT <- errormode[,c(1,4*c(1:11) + 1)]

  # Reformat data set
  errormodeA = errormodeA %>% dplyr::mutate(snr = cut(SNR_A, breaks)) %>% dplyr::group_by(snr) %>% dplyr::summarise(Insert_A = mean(A_InsertA), AinsertAci = sd(A_InsertA)/sqrt(n()) * qt(0.975, n() - 1), Insert_C = mean(A_InsertC), AinsertCci = sd(A_InsertC)/sqrt(n()) * qt(0.975, n() - 1), Insert_G = mean(A_InsertG), AinsertGci = sd(A_InsertG)/sqrt(n()) * qt(0.975, n() - 1), Insert_T = mean(A_InsertT), AinsertTci = sd(A_InsertT)/sqrt(n()) * qt(0.975, n() - 1), misMatch_C = mean(A_misMatchC), AmisMatchCci = sd(A_misMatchC)/sqrt(n()) * qt(0.975, n() - 1), misMatch_G = mean(A_misMatchG), AmisMatchGci = sd(A_misMatchG)/sqrt(n()) * qt(0.975, n() - 1), misMatch_T = mean(A_misMatchT), AmisMatchTci = sd(A_misMatchT)/sqrt(n()) * qt(0.975, n() - 1),Dark = mean(A_Dark), Adarci = sd(A_Dark)/sqrt(n()) * qt(0.975, n() - 1),Merge = mean(A_Merge), Ameci = sd(A_Merge)/sqrt(n()) * qt(0.975, n() - 1)) %>% dplyr::ungroup()
  dAinsert = cbind(melt(errormodeA[,c(1,2,4,6,8)], id.vars = "snr"), melt(errormodeA[,c(1,3,5,7,9)], id.vars = "snr"))[,c(1,2,3,6)]
  dAmisMatch = cbind(melt(errormodeA[,c(1,10,12,14)], id.vars = "snr"), melt(errormodeA[,c(1,11,13,15)], id.vars = "snr"))[,c(1,2,3,6)]
  dAdelete = cbind(melt(errormodeA[,c(1,16,18)], id.vars = "snr"), melt(errormodeA[,c(1,17,19)], id.vars = "snr"))[,c(1,2,3,6)]
  levels(dAinsert$snr) = breaks
  levels(dAmisMatch$snr) = breaks
  levels(dAdelete$snr) = breaks
  
  errormodeC = errormodeC %>% dplyr::mutate(snr = cut(SNR_C, breaks)) %>% dplyr::group_by(snr) %>% dplyr::summarise(Insert_A = mean(C_InsertA), CinsertAci = sd(C_InsertA)/sqrt(n()) * qt(0.975, n() - 1), Insert_C = mean(C_InsertC), CinsertCci = sd(C_InsertC)/sqrt(n()) * qt(0.975, n() - 1), Insert_G = mean(C_InsertG), CinsertGci = sd(C_InsertG)/sqrt(n()) * qt(0.975, n() - 1), Insert_T = mean(C_InsertT), CinsertTci = sd(C_InsertT)/sqrt(n()) * qt(0.975, n() - 1), misMatch_A = mean(C_misMatchA), CmisMatchAci = sd(C_misMatchA)/sqrt(n()) * qt(0.975, n() - 1), misMatch_G = mean(C_misMatchG), CmisMatchGci = sd(C_misMatchG)/sqrt(n()) * qt(0.975, n() - 1), misMatch_T = mean(C_misMatchT), CmisMatchTci = sd(C_misMatchT)/sqrt(n()) * qt(0.975, n() - 1),Dark = mean(C_Dark), Cdarci = sd(C_Dark)/sqrt(n()) * qt(0.975, n() - 1), Merge = mean(C_Merge), Cmeci = sd(C_Merge)/sqrt(n()) * qt(0.975, n() - 1)) %>% dplyr::ungroup()
  dCinsert = cbind(melt(errormodeC[,c(1,2,4,6,8)], id.vars = "snr"), melt(errormodeC[,c(1,3,5,7,9)], id.vars = "snr"))[,c(1,2,3,6)]
  dCmisMatch = cbind(melt(errormodeC[,c(1,10,12,14)], id.vars = "snr"), melt(errormodeC[,c(1,11,13,15)], id.vars = "snr"))[,c(1,2,3,6)]
  dCdelete = cbind(melt(errormodeC[,c(1,16,18)], id.vars = "snr"), melt(errormodeC[,c(1,17,19)], id.vars = "snr"))[,c(1,2,3,6)]
  levels(dCinsert$snr) = breaks
  levels(dCmisMatch$snr) = breaks
  levels(dCdelete$snr) = breaks
  
  errormodeG = errormodeG %>% dplyr::mutate(snr = cut(SNR_G, breaks)) %>% dplyr::group_by(snr) %>% dplyr::summarise(Insert_A = mean(G_InsertA), GinsertAci = sd(G_InsertA)/sqrt(n()) * qt(0.975, n() - 1), Insert_C = mean(G_InsertC), GinsertCci = sd(G_InsertC)/sqrt(n()) * qt(0.975, n() - 1), Insert_G = mean(G_InsertG), GinsertGci = sd(G_InsertG)/sqrt(n()) * qt(0.975, n() - 1), Insert_T = mean(G_InsertT), GinsertTci = sd(G_InsertT)/sqrt(n()) * qt(0.975, n() - 1), misMatch_A = mean(G_misMatchA), GmisMatchAci = sd(G_misMatchA)/sqrt(n()) * qt(0.975, n() - 1), misMatch_C = mean(G_misMatchC), GmisMatchCci = sd(G_misMatchC)/sqrt(n()) * qt(0.975, n() - 1), misMatch_T = mean(G_misMatchT), GmisMatchTci = sd(G_misMatchT)/sqrt(n()) * qt(0.975, n() - 1),Dark = mean(G_Dark), Gdarci = sd(G_Dark)/sqrt(n()) * qt(0.975, n() - 1),Merge = mean(G_Merge), Gmeci = sd(G_Merge)/sqrt(n()) * qt(0.975, n() - 1)) %>% dplyr::ungroup()
  dGinsert = cbind(melt(errormodeG[,c(1,2,4,6,8)], id.vars = "snr"), melt(errormodeG[,c(1,3,5,7,9)], id.vars = "snr"))[,c(1,2,3,6)]
  dGmisMatch = cbind(melt(errormodeG[,c(1,10,12,14)], id.vars = "snr"), melt(errormodeG[,c(1,11,13,15)], id.vars = "snr"))[,c(1,2,3,6)]
  dGdelete = cbind(melt(errormodeG[,c(1,16,18)], id.vars = "snr"), melt(errormodeG[,c(1,17,19)], id.vars = "snr"))[,c(1,2,3,6)]
  levels(dGinsert$snr) = breaks
  levels(dGmisMatch$snr) = breaks
  levels(dGdelete$snr) = breaks
  
  errormodeT = errormodeT %>% dplyr::mutate(snr = cut(SNR_T, breaks)) %>% dplyr::group_by(snr) %>% dplyr::summarise(Insert_A = mean(T_InsertA), TinsertAci = sd(T_InsertA)/sqrt(n()) * qt(0.975, n() - 1), Insert_C = mean(T_InsertC), TinsertCci = sd(T_InsertC)/sqrt(n()) * qt(0.975, n() - 1), Insert_G = mean(T_InsertG), TinsertGci = sd(T_InsertG)/sqrt(n()) * qt(0.975, n() - 1), Insert_T = mean(T_InsertT), TinsertTci = sd(T_InsertT)/sqrt(n()) * qt(0.975, n() - 1), misMatch_A = mean(T_misMatchA), TmisMatchAci = sd(T_misMatchA)/sqrt(n()) * qt(0.975, n() - 1), misMatch_C = mean(T_misMatchC), TmisMatchCci = sd(T_misMatchC)/sqrt(n()) * qt(0.975, n() - 1), misMatch_G = mean(T_misMatchG), TmisMatchGci = sd(T_misMatchG)/sqrt(n()) * qt(0.975, n() - 1),Dark = mean(T_Dark), Tdarci = sd(T_Dark)/sqrt(n()) * qt(0.975, n() - 1),Merge = mean(T_Merge), Tmeci = sd(T_Merge)/sqrt(n()) * qt(0.975, n() - 1)) %>% dplyr::ungroup()
  dTinsert = cbind(melt(errormodeT[,c(1,2,4,6,8)], id.vars = "snr"), melt(errormodeT[,c(1,3,5,7,9)], id.vars = "snr"))[,c(1,2,3,6)]
  dTmisMatch = cbind(melt(errormodeT[,c(1,10,12,14)], id.vars = "snr"), melt(errormodeT[,c(1,11,13,15)], id.vars = "snr"))[,c(1,2,3,6)]
  dTdelete = cbind(melt(errormodeT[,c(1,16,18)], id.vars = "snr"), melt(errormodeT[,c(1,17,19)], id.vars = "snr"))[,c(1,2,3,6)]
  levels(dTinsert$snr) = breaks
  levels(dTmisMatch$snr) = breaks
  levels(dTdelete$snr) = breaks
  
  # Fishbone Plots - Insertion
  tpA = ggplot(dAinsert, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR A", y = "HMM Error - A") + xlim(0,20) + ylim(-0.01,0.05) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpC = ggplot(dCinsert, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR C", y = "HMM Error - C") + xlim(0,20) + ylim(-0.01,0.05) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpG = ggplot(dGinsert, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR G", y = "HMM Error - G") + xlim(0,20) + ylim(-0.01,0.05) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpT = ggplot(dTinsert, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR T", y = "HMM Error - T") + xlim(0,20) + ylim(-0.01,0.05) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  
  png(paste(img_path, "FishbonePlot_Insertion.png", sep = ""), width = 1600, height = 1200)
  grid.arrange(tpA, tpC, tpG, tpT, ncol = 1)
  dev.off()
  
  # Fishbone Plots - Deletion
  tpA = ggplot(dAdelete, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR A", y = "HMM Error - A") + xlim(0,20) + ylim(-0.02,0.12) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpC = ggplot(dCdelete, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR C", y = "HMM Error - C") + xlim(0,20) + ylim(-0.02,0.12) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpG = ggplot(dGdelete, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR G", y = "HMM Error - G") + xlim(0,20) + ylim(-0.02,0.12) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpT = ggplot(dTdelete, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR T", y = "HMM Error - T") + xlim(0,20) + ylim(-0.02,0.12) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  
  png(paste(img_path, "FishbonePlot_Deletion.png", sep = ""), width = 800, height = 1200)
  grid.arrange(tpA, tpC, tpG, tpT, ncol = 1)
  dev.off()
  
  # Fishbone Plots - misMatch
  # Create Empty plots
  newrow = c(1, "  ", NA, NA)
  
  dAmisMatch$variable = as.character(dAmisMatch$variable)
  dAmisMatch = rbind(newrow, dAmisMatch)
  dAmisMatch$value = as.numeric(dAmisMatch$value)
  dAmisMatch$value.1 = as.numeric(dAmisMatch$value.1)
  dAmisMatch$variable <- factor(dAmisMatch$variable, levels = c("  ", "misMatch_C", "misMatch_G", "misMatch_T"))
  
  dCmisMatch$variable = as.character(dCmisMatch$variable)
  dCmisMatch = rbind(newrow, dCmisMatch)
  dCmisMatch$value = as.numeric(dCmisMatch$value)
  dCmisMatch$value.1 = as.numeric(dCmisMatch$value.1)
  dCmisMatch$variable <- factor(dCmisMatch$variable, levels = c("misMatch_A", "  ", "misMatch_G", "misMatch_T"))
  
  dGmisMatch$variable = as.character(dGmisMatch$variable)
  dGmisMatch = rbind(newrow, dGmisMatch)
  dGmisMatch$value = as.numeric(dGmisMatch$value)
  dGmisMatch$value.1 = as.numeric(dGmisMatch$value.1)
  dGmisMatch$variable <- factor(dGmisMatch$variable, levels = c("misMatch_A", "misMatch_C", "  ", "misMatch_T"))
  
  dTmisMatch$variable = as.character(dTmisMatch$variable)
  dTmisMatch = rbind(newrow, dTmisMatch)
  dTmisMatch$value = as.numeric(dTmisMatch$value)
  dTmisMatch$value.1 = as.numeric(dTmisMatch$value.1)
  dTmisMatch$variable <- factor(dTmisMatch$variable, levels = c("misMatch_A", "misMatch_C", "misMatch_G", "  "))
  
  tpA = ggplot(dAmisMatch, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR A", y = "HMM Error - A") + xlim(0,20) + ylim(0,0.1) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpC = ggplot(dCmisMatch, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR C", y = "HMM Error - C") + xlim(0,20) + ylim(0,0.1) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpG = ggplot(dGmisMatch, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR G", y = "HMM Error - G") + xlim(0,20) + ylim(0,0.1) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  tpT = ggplot(dTmisMatch, aes(x = as.numeric(as.character(snr)), y = value)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = value - value.1, ymax = value + value.1), width = .1, position = pd) + labs(x = "SNR T", y = "HMM Error - T") + xlim(0,20) + ylim(0,0.1) + facet_wrap(~variable, nrow = 1) + plTheme + clScale + themeTilt
  
  png(paste(img_path, "FishbonePlot_misMatch.png", sep = ""), width = 1600, height = 1200)
  grid.arrange(tpA, tpC, tpG, tpT, ncol = 1)
  dev.off()
  
}

# makeFishbonePlots(input_csv, img_path)

makeFishbonePlotsRtc <- function(rtc) {
  return(
    makeFishbonePlots(
      rtc@task@inputFiles[1],
      rtc@task@outputFiles[1]
    )
  )
}

# Example populated Registry for testing
#' @export
PBIReseqconditionRegistryBuilder <- function() {
  r <- registryBuilder(PB_TOOL_NAMESPACE, "fishbonePlot.R run-rtc ")
  
  registerTool(
    r,
    "fishbonePlot",
    "0.0.1",
    c(FileTypes$CSV),
    c(FileTypes$PNG),
    16,
    TRUE,
    makeFishbonePlotsRtc
  )
  return(r)
}

## Add this line to enable logging
basicConfig()
q(status = mainRegisteryMainArgs(PBIReseqconditionRegistryBuilder()))
