#!/usr/bin/env Rscript
# Fit a constant rate arrow model to an alignment/reference and output the
# parameters as a CSV
# Make finshbone plots from a csv file generated by fitting hmm model
# This script combines constant_arrow.R and FishbonePlotsCmdLine.R

library(argparse)
library(data.table)
library(jsonlite, quietly = TRUE)
library(logging)
library(ggplot2)
library(pbbamr)
library(uuid, quietly = TRUE)
library(gridExtra)
library(dplyr)
library(tidyr)
library(unitem)
library(nnet)
library(reshape2)
library(lazyeval)
library(gtable)
require(grid)

## FIXME: make a real package
myDir = "./scripts/R"
source(file.path(myDir, "Bauhaus2.R"))

# Define a basic addition to all plots
plTheme <- theme_bw(base_size = 18)
clScale <- scale_colour_brewer(palette = "Set1")
clFillScale <- scale_fill_brewer(palette = "Set1")
themeTilt = theme(
  panel.border = element_blank(),
  panel.grid.minor = element_blank(),
  panel.spacing = unit(4 / 3, "lines"),
  strip.background = element_blank(),
  strip.text.y = element_text(angle = 0),
  plot.title = element_text(hjust = 0.5)
)
pd <- position_dodge(0.2)
dpi <- 160

set_panel_heights <- function(g, heights) {
  g$heights <- grid:::unit.list(g$heights)
  id_panels <-
    unique(c(g$layout[g$layout$name == "panel-1-1", "t"], g$layout[g$layout$name == "panel-2-1", "t"], g$layout[g$layout$name == "panel-3-1", "t"], g$layout[g$layout$name == "panel-4-1", "t"]))
  g$heights[id_panels] <- unit(heights, "null")
  g
}

makeFishbonePlots <-
  function(errormodeMerge, report, minSample = 20) {
    loginfo("making fishbone plots.")

    # some functions
    concat <- function(...)
      paste(..., sep = "")
    nam <- function(...)
      as.name(concat(...))

    # functions to add SNR density plots to Insert/Mismatch hmm plots
    generateFixAxisPlot <- function(df, dfSNR_, dfSNRall_, maxSNR) {
      tp = ggplot(df,
                  aes(
                    x = as.numeric(as.character(snr)),
                    y = mu,
                    group = Condition,
                    colour = Condition
                  )) +
        geom_point(aes(colour = Condition)) + geom_line(aes(colour = Condition)) +
        geom_errorbar(
          aes(
            ymin = mu - ci,
            ymax = mu + ci,
            colour = Condition
          ),
          width = 0.1,
          position = pd
        ) +
        geom_vline(aes(xintercept = value, colour = Condition),
                   dfSNR_) +
        labs(y = "Error Rate") +
        coord_fixed(ratio = ratio) +
        plTheme + clScale + themeTilt + theme(axis.title.x = element_blank()) +
        annotate(
          "segment",
          x = -Inf,
          xend = Inf,
          y = -Inf,
          yend = -Inf,
          size = 1
        ) +
        annotate(
          "segment",
          x = -Inf,
          xend = -Inf,
          y = -Inf,
          yend = Inf,
          size = 1
        )

      tp1 = tp + xlim(xlimits) +
        scale_y_continuous(limits = ylimits, breaks = breaks) + facet_grid(exp_ ~ obs_)

      tpdensity = ggplot(dfSNRall_, aes(x = as.numeric(as.character(snr)), colour = Condition)) +
        geom_density(alpha = .5) + plTheme + clScale + themeTilt +
        labs(x = "SNR", y = "SNR Density") +
        annotate(
          "segment",
          x = -Inf,
          xend = Inf,
          y = -Inf,
          yend = -Inf,
          size = 1
        ) +
        annotate(
          "segment",
          x = -Inf,
          xend = -Inf,
          y = -Inf,
          yend = Inf,
          size = 1
        )
      tpdensityfix = tpdensity + facet_grid(SNRlabel ~ obs_) + xlim(0, maxSNR) + theme(strip.text.x = element_blank(), axis.title.x = element_blank())
      pdf(NULL)
      g1 <- ggplotGrob(tp1)
      g3 <- ggplotGrob(tpdensityfix)
      gfix <- rbind(g1, g3, size = "first")
      gfix$widths <- unit.pmax(g1$widths, g3$widths)
      gfix <-
        set_panel_heights(gfix, rep(0.6, 5))
      gfix
    }

    generateFreeAxisPlot <- function(df, dfSNR_, type, dfSNRall_) {
      tmp = data.frame(matrix(rep(NA, 88), nrow = 8, ncol = 11))
      names(tmp) = names(df)
      tmp$exp_ = c(rep("A", 2), rep("C", 2), rep("G", 2), rep("T", 2))
      tmp$obs_ = tmp$exp
      tmp$mu = 0

      ylimitsBase <- function(Base) {
        range(c(df[df$exp == Base, ]$mu - df[df$exp == Base, ]$ci, df[df$exp == Base, ]$mu + df[df$exp == Base, ]$ci))
      }

      tmp$mu = c(ylimitsBase("A"),
                 ylimitsBase("C"),
                 ylimitsBase("G"),
                 ylimitsBase("T"))
      tmp$ci = 0
      tmp$Condition = df$Condition[1]

      tpBase <- function(Base) {
        tp = ggplot(rbind(tmp, df[df$obs == Base, ]),
                    aes(
                      x = as.numeric(as.character(snr)),
                      y = mu,
                      group = Condition,
                      colour = Condition
                    )) +
          geom_point(aes(colour = Condition)) + geom_line(aes(colour = Condition)) +
          geom_errorbar(
            aes(
              ymin = mu - ci,
              ymax = mu + ci,
              colour = Condition
            ),
            width = 0.1,
            position = pd
          ) +
          geom_vline(aes(xintercept = value, colour = Condition),
                     dfSNR_[dfSNR_$obs_ == paste(type, Base, sep = " "), ]) +
          labs(y = "Error Rate", title = paste(type, Base, sep = " ")) +
          coord_fixed(ratio = ratio) +
          plTheme + clScale + themeTilt + theme(axis.title.x = element_blank()) +
          annotate(
            "segment",
            x = -Inf,
            xend = Inf,
            y = -Inf,
            yend = -Inf,
            size = 1
          ) +
          annotate(
            "segment",
            x = -Inf,
            xend = -Inf,
            y = -Inf,
            yend = Inf,
            size = 1
          )
        tp
      }

      tp2A = tpBase("A") + facet_grid(exp_ ~ ., scales = "free") + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        strip.text.y = element_blank(),
        plot.title = element_text(size = 14)
      )
      tp2C = tpBase("C") + facet_grid(exp_ ~ ., scales = "free") + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        strip.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.title = element_text(size = 14)
      )
      tp2G = tpBase("G") + facet_grid(exp_ ~ ., scales = "free") + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        strip.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.title = element_text(size = 14)
      )
      tp2T = tpBase("T") + facet_grid(exp_ ~ ., scales = "free") + theme(
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.title = element_text(size = 14)
      )

      tp2Alimit = tp2A + xlim(ggplot_build(tp2A)$layout$panel_ranges[[1]]$x.range)
      tp2Climit = tp2C + xlim(ggplot_build(tp2C)$layout$panel_ranges[[1]]$x.range)
      tp2Glimit = tp2G + xlim(ggplot_build(tp2G)$layout$panel_ranges[[1]]$x.range)
      tp2Tlimit = tp2T + xlim(ggplot_build(tp2T)$layout$panel_ranges[[1]]$x.range)

      pdf(NULL)
      g2A <- ggplotGrob(tp2Alimit)
      g2C <- ggplotGrob(tp2Climit)
      g2G <- ggplotGrob(tp2Glimit)
      g2T <- ggplotGrob(tp2Tlimit)

      g2free <- cbind(g2A, g2C, g2G, g2T, size = "first")

      tpdensityBase <- function(Base) {
        tpdensityA = ggplot(dfSNRall_[dfSNRall_$obs == Base, ], aes(x = as.numeric(as.character(snr)), colour = Condition)) +
          geom_density(alpha = .5) + plTheme + clScale + themeTilt +
          labs(x = "SNR", y = "SNR Density") +
          annotate(
            "segment",
            x = -Inf,
            xend = Inf,
            y = -Inf,
            yend = -Inf,
            size = 1
          ) +
          annotate(
            "segment",
            x = -Inf,
            xend = -Inf,
            y = -Inf,
            yend = Inf,
            size = 1
          )
      }

      tpdensityfreeA = tpdensityBase("A") + facet_grid(SNRlabel ~ obs_) + xlim(ggplot_build(tp2A)$layout$panel_ranges[[1]]$x.range) + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        strip.text.x = element_blank()
      )
      tpdensityfreeC = tpdensityBase("C") + facet_grid(SNRlabel ~ obs_) + xlim(ggplot_build(tp2C)$layout$panel_ranges[[1]]$x.range) + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.x = element_blank()
      )
      tpdensityfreeG = tpdensityBase("G") + facet_grid(SNRlabel ~ obs_) + xlim(ggplot_build(tp2G)$layout$panel_ranges[[1]]$x.range) + theme(
        legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.x = element_blank()
      )
      tpdensityfreeT = tpdensityBase("T") + facet_grid(SNRlabel ~ obs_) + xlim(ggplot_build(tp2T)$layout$panel_ranges[[1]]$x.range) + theme(
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.x = element_blank()
      )

      tpDensityYlimits = range(
        ggplot_build(tpdensityfreeA)$layout$panel_ranges[[1]]$y.range,
        ggplot_build(tpdensityfreeC)$layout$panel_ranges[[1]]$y.range,
        ggplot_build(tpdensityfreeG)$layout$panel_ranges[[1]]$y.range,
        ggplot_build(tpdensityfreeT)$layout$panel_ranges[[1]]$y.range
      )

      pdf(NULL)
      gA <- ggplotGrob(tpdensityfreeA + ylim(tpDensityYlimits))
      gC <- ggplotGrob(tpdensityfreeC + ylim(tpDensityYlimits))
      gG <- ggplotGrob(tpdensityfreeG + ylim(tpDensityYlimits))
      gT <- ggplotGrob(tpdensityfreeT + ylim(tpDensityYlimits))

      g4free <- cbind(gA, gC, gG, gT, size = "first")

      gfree <- rbind(g2free, g4free, size = "first")
      gfree
    }

    # Filter the ZMWs with SNR = 0 and NAs
    errormodeMerge <- errormodeMerge %>% na.omit()
    errormodeMerge <-
      dplyr::filter(errormodeMerge, SNR.A > 0 &
                      SNR.C > 0 & SNR.G > 0 & SNR.T > 0)
    maxSNR = (round(max(errormodeMerge$SNR.A, errormodeMerge$SNR.C, errormodeMerge$SNR.G, errormodeMerge$SNR.T)) + 1)
    breaks = c(0, 1:(1.5*maxSNR))/1.5
    bases <- c("A", "C", "G", "T")

    massage <- function(df, channel) {
      # filter on data specifically under the expectation of the channel base
      ch <- concat(channel, ".")
      re <- concat("^", channel, "\\.")
      df <- df %>%
        dplyr::select(ZMW, starts_with("SNR."), starts_with(ch)) %>%
        dplyr::rename_(.dots = setNames(names(.), gsub(re, "", names(.))))

      ci95 <-
        function(var)
          interp(~ sd(x) / sqrt(n()) * qt(0.975, n() - 1), x = lazy(var))
      mvNams <-
        function(b, moves)
          unlist(lapply(c(moves), function(x)
            concat(x, ".", b)))
      stNams <-
        function(b, moves)
          unlist(lapply(c(moves), function(x)
            concat(x, ".", b, ".", c("mu", "ci"))))

      # collect the results for each outcome base
      dfCh <- NULL

      for (b in bases) {
        # get the transition moves under the regime of expectedBase:observedBase
        moves <-
          gsub(".[ACGT]$", "", colnames(dplyr::select(
            df, ends_with(concat(".", b)), -starts_with("SNR")
          )))

        # get the raw move names
        nms <- mvNams(b, moves)

        # prepare the mean- and 95%ci-accumulating functions
        mus <-
          lapply(nms, function(x)
            interp(~ mean(y), y = as.name(x)))
        cis <-
          lapply(nms, function(x)
            eval(interp(ci95(y), y = as.name(x))))

        # create the interleaved list of mean- and 95%ci-accumulating functions
        obj <- c(rbind(mus, cis))

        # get the names of the statistical variables
        nms <- stNams(b, moves)

        # add the number of observations to the list of variables (for later filtering)
        obj <- c(obj, ~ n())
        nms <- c(nms, "N")

        # group the samples by their SNR bin and collect summary mean and 95%ci
        suppressWarnings({
          dfStats <- df %>%
            dplyr::select(ZMW, ends_with(concat(".", b))) %>%
            dplyr::mutate_(snr = interp(~ cut(x, breaks), x = nam("SNR.", b))) %>%
            dplyr::select(-starts_with("SNR.")) %>%
            dplyr::group_by(snr) %>%
            dplyr::summarize_(.dots = setNames(obj, nms)) %>%
            dplyr::ungroup()
        })

        # melt the data on which move and accumulate
        dfObs <- NULL

        for (mv in moves) {
          dfMv <- dfStats %>%
            dplyr::select(snr, starts_with(mv), N) %>%
            dplyr::rename_(.dots = setNames(names(.), gsub(
              concat(mv, "\\.", b, "\\."), "", names(.)
            ))) %>%
            dplyr::mutate(move = mv)
          dfObs <- rbind(dfObs, dfMv)
        }

        dfObs$obs <- b
        dfCh <- rbind(dfCh, dfObs)
      }

      dfCh$exp <- channel
      dfCh
    }

    # collect the results over each expected match base
    dfErr = list()

    readcondition = errormodeMerge$Condition
    for (i in 1:length(readcondition)) {
      dfErr[[i]] = NA
      for (b in bases) {
        dfErr[[i]] <-
          rbind(dfErr[[i]], massage(errormodeMerge[errormodeMerge$Condition == readcondition[i],], b))
        dfErr[[i]] = dfErr[[i]][c(2:nrow(dfErr[[i]])),]
      }
      # make sure things are factors and the appropriate levels
      levels(dfErr[[i]]$snr) <-
        head(breaks, length(levels(dfErr[[i]]$snr)))
      dfErr[[i]]$move <- as.factor(dfErr[[i]]$move)
      dfErr[[i]]$exp <- as.factor(dfErr[[i]]$exp)
      dfErr[[i]]$obs <- as.factor(dfErr[[i]]$obs)
      dfErr[[i]] <- as.data.frame(dfErr[[i]])
      row.names(dfErr[[i]]) <- seq.int(nrow(dfErr[[i]]))
      # Add Condition name from the input file names
      dfErr[[i]]$Condition = readcondition[i]
    }
    # write the data
    dfErr = do.call(rbind, dfErr)
    report$write.table("FishboneSnrBinnedSummary.csv",
                       dfErr,
                       id = "fishbone_snr_binned_summary",
                       title = "Fishbone Snr Binned Summary")

    ## WRITE THE PLOTS ##
    # filter by min number of samples in each SNR bin
    dfErr_ <- dfErr %>% filter(N >= minSample)
    loginfo("filtered %d of %d samples",
            nrow(dfErr) - nrow(dfErr_),
            nrow(dfErr))
    if (nrow(dfErr_) == 0) {
      warning("You have filtered out all of your data and need to increase the Min Sample!")
      report = 0
    } else {
      t <-
        function(mv)
          ifelse(mv == "Match", "Mismatch", as.character(mv))

      dfErr_ <- dfErr_ %>%
        dplyr::mutate(exp_ = exp, obs_ = concat(t(move), " ", obs))
      dfErr_$exp_ <- as.factor(dfErr_$exp_)
      dfErr_$obs_ <- as.factor(dfErr_$obs_)
      dfErr_$SNRlabel = ""

      labelFn <- function(x) {
        sprintf("%0.2f", x)
      }
      breaksFn <- function(x) {
        seq(x[[1]], x[[2]], by = 0.05)
      }

      df = errormodeMerge
      dfSNRall <- df %>%
        select(Condition, starts_with("SNR.")) %>%
        dplyr::rename_(.dots = setNames(names(.), gsub("SNR.", "", names(.)))) %>%
        melt(id.vars = c("Condition"),
             variable.name = "obs_")
      dfSNR <- dfSNRall %>%
        group_by(Condition, obs_) %>%
        summarise(value = mean(value))

      addMove <-
        function(df, mv)
          df %>% dplyr::mutate(obs_ = concat(mv, " ", obs_))

      golden_ratio <- 1.618
      xlimits <- c(0, maxSNR)
      ylimits <- c(0, 0.15)
      ratio <- xlimits[[2]] / ylimits[[2]] / golden_ratio
      dfIns <- dfErr_ %>% filter(move == "Insert")
      breaks <- breaksFn(ylimits)

      dfSNR_ = dfSNR %>% addMove("Insert")
      dfSNRall$SNRlabel = ""
      dfSNRall_ <- dplyr::rename(dfSNRall, snr = value, obs = obs_)
      dfSNRall_$obs_ = paste("Insert", dfSNRall_$obs)
      gInsFix = generateFixAxisPlot(dfIns, dfSNR_, dfSNRall_, maxSNR)
      gInsFree = generateFreeAxisPlot(dfIns, dfSNR_, "Insert", dfSNRall_)

      report$ggsave(
        "fishboneplot_insertion.png",
        gInsFix,
        width = 2000 / dpi,
        height = 1600 / dpi,
        units = "in",
        id = "fishboneplot_insertion",
        title = "FishbonePlot - Insertion",
        caption = "FishbonePlot - Insertion",
        tags = c("fishbone", "hmm", "errormode", "insertion"),
        uid = "0010001"
      )
      report$ggsave(
        "fishboneplot_insertion_enlarged.png",
        gInsFree,
        width = 2000 / dpi,
        height = 1600 / dpi,
        units = "in",
        id = "fishboneplot_insertion_enlarged",
        title = "FishbonePlot - Insertion (Enlarged)",
        caption = "FishbonePlot - Insertion (Enlarged)",
        tags = c("fishbone", "hmm", "errormode", "insertion", "enlarged"),
        uid = "0010002"
      )
      dfSNR_ <-
        do.call(rbind, lapply(bases, function(b) {
          dfSNR %>% transform(exp_ = b)
        })) %>%
        filter(obs_ != exp_) %>%
        addMove("Mismatch")
      dfSNRM_ <- dfSNR_

      dfMM <- dfErr_ %>% filter(move == "Match" & obs != exp)
      breaks <- breaksFn(ylimits)
      dfSNRall_ <- dfSNRall %>% rename(snr = value, obs = obs_)
      dfSNRall_$obs_ = paste("Mismatch", dfSNRall_$obs)
      gMMFix = generateFixAxisPlot(dfMM, dfSNR_, dfSNRall_, maxSNR)
      gMMFree = generateFreeAxisPlot(dfMM, dfSNR_, "Mismatch", dfSNRall_)
      report$ggsave(
        "fishboneplot_mismatch.png",
        gMMFix,
        width = 2000 / dpi,
        height = 1600 / dpi,
        units = "in",
        id = "fishboneplot_mismatch",
        title = "FishbonePlot - MisMatch",
        caption = "FishbonePlot - MisMatch",
        tags = c("fishbone", "hmm", "errormode", "mismatch"),
        uid = "0010003"
      )
      report$ggsave(
        "fishboneplot_mismatch_enlarged.png",
        gMMFree,
        width = 2000 / dpi,
        height = 1600 / dpi,
        units = "in",
        id = "fishboneplot_mismatch_enlarged",
        title = "FishbonePlot - MisMatch (Enlarged)",
        caption = "FishbonePlot - MisMatch (Enlarged)",
        tags = c("fishbone", "hmm", "errormode", "mismatch", "enlarged"),
        uid = "0010004"
      )

      dfSNR_ <-
        rbind(dfSNR %>% transform(move = "Dark"),
              dfSNR %>% transform(move = "Merge")) %>% dplyr::rename(exp_ = obs_, obs_ = move)
      dfDel <- dfErr_ %>% filter(move == "Dark" | move == "Merge")
      breaks <- breaksFn(ylimits)
      tp = ggplot(dfDel,
                  aes(
                    x = as.numeric(as.character(snr)),
                    y = mu,
                    group = Condition,
                    colour = Condition
                  )) +
        geom_point(aes(colour = Condition)) + geom_line(aes(colour = Condition)) +
        geom_errorbar(
          aes(
            ymin = mu - ci,
            ymax = mu + ci,
            colour = Condition
          ),
          width = 0.1,
          position = pd
        ) +
        geom_vline(aes(xintercept = value, colour = Condition), dfSNR_) +
        labs(x = "SNR", y = "Error Rate") +
        coord_fixed(ratio = ratio) +
        plTheme + clScale + themeTilt +
        annotate(
          "segment",
          x = -Inf,
          xend = Inf,
          y = -Inf,
          yend = -Inf,
          size = 1
        ) +
        annotate(
          "segment",
          x = -Inf,
          xend = -Inf,
          y = -Inf,
          yend = Inf,
          size = 1
        )
      tp1 = tp + facet_grid(exp_ ~ move) +
        scale_y_continuous(limits = ylimits, breaks = breaks) + xlim(xlimits)
      report$ggsave(
        "fishboneplot_deletion.png",
        tp1,
        width = 1800 / dpi,
        height = 1200 / dpi,
        units = "in",
        id = "fishboneplot_deletion",
        title = "FishbonePlot - Deletion",
        caption = "FishbonePlot - Deletion",
        tags = c("fishbone", "hmm", "errormode", "deletion"),
        uid = "0010005"
      )
      tp2 = tp + facet_grid(exp_ ~ move, scales = "free")
      report$ggsave(
        "fishboneplot_deletion_enlarged.png",
        tp2,
        width = 1800 / dpi,
        height = 1200 / dpi,
        units = "in",
        id = "fishboneplot_deletion_enlarged",
        title = "FishbonePlot - Deletion (Enlarged)",
        caption = "FishbonePlot - Deletion (Enlarged)",
        tags = c("fishbone", "hmm", "errormode", "deletion", "enlarged"),
        uid = "0010006"
      )

      # Plot a merged fishbone plot that contains insetion, deletion and mismatch
      dfSNRM_ = rbind((do.call(rbind, lapply(bases, function(b) {
        dfSNR %>% transform(exp_ = b)
      })) %>% addMove("Insert")), dfSNR_, dfSNRM_)
      dfSNRM_ = dfSNRM_[order(dfSNRM_$exp_), , drop = FALSE]
      dfSNRM_$obs_ = factor(
        dfSNRM_$obs_,
        levels = c(
          "Insert A",
          "Insert C",
          "Insert G",
          "Insert T",
          "Dark",
          "Merge",
          "Mismatch A",
          "Mismatch C",
          "Mismatch G",
          "Mismatch T"
        )
      )
      dfMerge <-
        dfErr_ %>% filter(move == "Dark" |
                            move == "Merge" |
                            move == "Insert" |
                            (move == "Match" & obs != exp))
      dfMerge$obs_ = as.vector(dfMerge$obs_)
      dfMerge$obs_[dfMerge$move == "Dark"] = "Dark"
      dfMerge$obs_[dfMerge$move == "Merge"] = "Merge"
      dfMerge$obs_ = factor(
        dfMerge$obs_,
        levels = c(
          "Insert A",
          "Insert C",
          "Insert G",
          "Insert T",
          "Dark",
          "Merge",
          "Mismatch A",
          "Mismatch C",
          "Mismatch G",
          "Mismatch T"
        )
      )
      breaks <- breaksFn(ylimits)
      tp = ggplot(dfMerge,
                  aes(
                    x = as.numeric(as.character(snr)),
                    y = mu,
                    colour = Condition,
                    group = Condition
                  )) +
        geom_point(aes(colour = Condition)) + geom_line(aes(colour = Condition)) + geom_errorbar(
          aes(
            ymin = mu - ci,
            ymax = mu + ci,
            colour = Condition
          ),
          width = 0.1,
          position = pd
        ) +
        geom_vline(aes(xintercept = value, colour = Condition), dfSNRM_) +
        labs(x = "SNR by Event", y = "HMM Error") +
        coord_fixed(ratio = ratio) +
        plTheme + clScale + themeTilt +
        annotate(
          "segment",
          x = -Inf,
          xend = Inf,
          y = -Inf,
          yend = -Inf,
          size = 1
        ) +
        annotate(
          "segment",
          x = -Inf,
          xend = -Inf,
          y = -Inf,
          yend = Inf,
          size = 1
        )
      tp1 = tp + facet_grid(exp_ ~ obs_) +
        scale_y_continuous(limits = ylimits, breaks = breaks) + xlim(xlimits)
      report$ggsave(
        "fishboneplot_merge.png",
        tp1,
        width = 3000 / dpi,
        height = 1200 / dpi,
        units = "in",
        id = "fishboneplot_merge",
        title = "FishbonePlot - Merge",
        caption = "FishbonePlot - Merge",
        tags = c("fishbone", "hmm", "errormode", "merge"),
        uid = "0010007"
      )
      tp2 = tp + facet_grid(exp_ ~ obs_, scales = "free")
      report$ggsave(
        "fishboneplot_merge_enlarged.png",
        tp2,
        width = 3000 / dpi,
        height = 1200 / dpi,
        units = "in",
        id = "fishboneplot_merge_enlarged",
        title = "FishbonePlot - Merge (Enlarged)",
        caption = "FishbonePlot - Merge (Enlarged)",
        tags = c("fishbone", "hmm", "errormode", "merge", "enlarged"),
        uid = "0010008"
      )
      dfErr
    }
  }

makeReport <- function(report) {
  conditions = report$condition.table
  n = length(levels(conditions$Condition))
  clFillScale <<- getPBFillScale(n)
  clScale <<- getPBColorScale(n)

  # Load csv files
  errormodeMerge = read.csv("reports/ConstantArrowFishbonePlots/errormode.csv")

  if (nrow(errormodeMerge) == 0) {
    warning("The Errormode CSV file is empty!")
  } else {
    # Make Fishbone Plots
    try(makeFishbonePlots(errormodeMerge, report), silent = TRUE)
    0
  }

  # Save the report object for later debugging
  save(report, file = file.path(report$outputDir, "report.Rd"))

  # At the end of this function we need to call this last, it outputs the report
  report$write.report()
}

main <- function()
{
  report <- bh2Reporter(
    "condition-table.csv",
    "reports/ConstantArrowFishbonePlots/report.json",
    "Constant Arrow Fishbone Plots"
  )
  makeReport(report)
  jsonFile = "reports/ConstantArrowFishbonePlots/report.json"
  uidTagCSV = "reports/uidTag.csv"
  if (file.exists(jsonFile)) {
    try(rewriteJSON(jsonFile, uidTagCSV), silent = TRUE)
  }
  0
}

## Leave this as the last line in the file.
logging::basicConfig()
main()
