library(argparse)
library(ggplot2)
library(pbbamr)

parser <- ArgumentParser()
parser$add_argument("--subreadset",
                    nargs = 1,
                    default = FALSE,
                    help = "path of the subreadset")
parser$add_argument("--txtReport",
                    nargs = 1,
                    default = FALSE,
                    help = "txt report generated by pbQcAdapters")
parser$add_argument("--tag",
                    nargs = 1,
                    default = FALSE,
                    help = "tag of the output plot")
parser$add_argument("--output",
                    nargs = 1,
                    default = FALSE,
                    help = "path of the output plot")
try(args <- parser$parse_args())
set.seed(args$seed)

# path to subreads.bam file:
bam = args$subreadset
# string label:
tag = args$tag
# path to text output of pbQcSubreads command line tool:
rfile = args$txtReport
x = loadPBI( bam )
s1 = split(1:nrow(x), x$hole)

r = subset(read.table(rfile), V3 != "PhantomAdapter")
s2 = split(1:nrow(r), r$V2)
m = match(names(s1), names(s2))

n2 = vapply(s2, length, 0)
n1 = vapply(s1, length, 0)
n12 = n2[m]
n12[is.na(n12)] <- 0

# data frame for plotting:n1 = number of detected adapters
# n2 = number of missed adapters
d = data.frame(zmw = names(s1), n1 = n1, n2 = n12)
s0 = subset(d, n1 > 4)
l1 = paste(nrow(s0), "ZMWs with > 4 identified subreads")
l2 = paste(
  sum(s0$n2 / s0$n1 > 0.25),
  " ZMWs with > 0.25 of its subreads \n containing missing adapters (",
  format(100 * mean(s0$n2 / s0$n1 > 0.25), digits = 4),
  "%)",
  sep = ""
)
png(args$output)
hist(
  s0$n2 / s0$n1,
  100,
  col = 'cyan',
  xlab = "Fraction of Missed Adapters",
  ylab = "# of ZMWs",
  main = tag
)
abline(v = 0.25, col = 'red')
legend("topright",
       legend = c(l1, l2),
       fill = c("cyan", "cyan"))
dev.off()